# Generated by Django 6.0 on 2026-02-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('RL', 'Representante Legal'), ('GER', 'Gerente'), ('TES', 'Tesorería'), ('CON', 'Contabilidad'), ('COM', 'Comercial'), ('OTR', 'Otro')], max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='tenancy.empresa')),
            ],
            options={
                'verbose_name': 'Contacto de Empresa',
                'verbose_name_plural': 'Contactos de Empresa',
                'ordering': ['empresa', 'tipo', 'nombre'],
            },
        ),
    ]
