# Generated by Django 6.0 on 2025-12-24 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona natural'), ('JURIDICA', 'Persona jurídica')], default='JURIDICA', max_length=20)),
                ('tipo_doc', models.CharField(max_length=30)),
                ('documento', models.CharField(max_length=40)),
                ('nombre1', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre2', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido1', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido2', models.CharField(blank=True, max_length=60, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('departamento', models.CharField(blank=True, max_length=80, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_regimen', models.CharField(blank=True, max_length=50, null=True)),
                ('responsabilidades_tributarias', models.TextField(blank=True, null=True)),
                ('email_facturacion_electronica', models.EmailField(blank=True, max_length=254, null=True)),
                ('rl_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('rl_tipo_doc', models.CharField(blank=True, max_length=30, null=True)),
                ('rl_documento', models.CharField(blank=True, max_length=40, null=True)),
                ('tes_contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('tes_cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('tes_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_aprobados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='tenancy.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudActualizacionTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('cambios', models.JSONField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_actualizacion_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_actualizacion', to='tenancy.empresa')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_actualizacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_actualizacion', to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(blank=True, max_length=120, null=True)),
                ('arl', models.CharField(blank=True, max_length=120, null=True)),
                ('afp', models.CharField(blank=True, max_length=120, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='terceros/seguridad_social/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tercero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social', to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='terceros/experiencia/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('COLEGIO', 'Colegio'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('PROFESIONAL', 'Profesional'), ('POSGRADO', 'Posgrado')], max_length=20)),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='terceros/estudios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('entidad', models.CharField(blank=True, max_length=200, null=True)),
                ('horas', models.PositiveIntegerField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='terceros/cursos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='terceros/certificaciones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='TerceroTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.tercero')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tipotercero')),
            ],
            options={
                'unique_together': {('tercero', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipos',
            field=models.ManyToManyField(related_name='terceros', through='terceros.TerceroTipo', to='terceros.tipotercero'),
        ),
        migrations.CreateModel(
            name='DocumentoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='terceros/anexos/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADO', 'Cargado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('firmado', models.BooleanField(default=False)),
                ('qr_value', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_integridad', models.CharField(blank=True, max_length=128, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_terceros', to='tenancy.empresa')),
                ('documento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.documentotipo')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='terceros.tercero')),
            ],
            options={
                'unique_together': {('tercero', 'documento_tipo')},
            },
        ),
        migrations.CreateModel(
            name='TerceroIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('NATIVO', 'Nativo')], max_length=20)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.idioma')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='terceros.tercero')),
            ],
            options={
                'unique_together': {('tercero', 'idioma')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tercero',
            unique_together={('empresa', 'tipo_doc', 'documento')},
        ),
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('documento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.documentotipo')),
                ('tipo_tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='terceros.tipotercero')),
            ],
            options={
                'unique_together': {('tipo_tercero', 'documento_tipo')},
            },
        ),
    ]
