# Generated by Django 6.0 on 2025-12-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_invitacionvinculacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionvinculacion',
            name='tipo_tercero',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones', to='terceros.tipotercero'),
            preserve_default=False,
        ),
    ]
