# Generated by Django 6.0 on 2026-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_invitacionvinculacion_tipo_tercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='tercerotipo',
            options={'verbose_name': 'Tipo de Tercero', 'verbose_name_plural': 'Tipos de Terceros'},
        ),
        migrations.AlterUniqueTogether(
            name='documentorequerido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentorequerido',
            name='aplica_a_persona',
            field=models.CharField(choices=[('AMBAS', 'Ambas'), ('NATURAL', 'Persona natural'), ('JURIDICA', 'Persona jurídica')], default='AMBAS', help_text='Indica si este documento aplica a personas naturales, jurídicas o ambas', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='documentorequerido',
            unique_together={('tipo_tercero', 'documento_tipo', 'aplica_a_persona')},
        ),
        migrations.AddField(
            model_name='tercero',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='terceros', to='terceros.tag'),
        ),
    ]
