# Generated by Django 6.0 on 2026-02-01 17:54

import terceros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_tag_alter_tercerotipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotercero',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=terceros.models.upload_doc_tercero),
        ),
    ]
