# Generated by Django 6.0 on 2026-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_alter_documentotercero_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='nivel',
            field=models.CharField(choices=[('BACHILLER', 'Bachiller'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('PROFESIONAL', 'Profesional'), ('POSGRADO', 'Posgrado')], max_length=20),
        ),
    ]
