# Generated by Django 6.0 on 2026-03-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0006_alter_estudio_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario vinculado para portal de terceros', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tercero_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TokenActivacionTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_activacion_tercero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
