# Generated by Django 6.0 on 2025-12-24 23:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('terceros', '0003_invitacionvinculacion_tipo_tercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Consecutivo o referencia de la cuenta de cobro.', max_length=50)),
                ('periodo', models.CharField(help_text='Ej: 2025-12, Noviembre 2025, etc.', max_length=50)),
                ('concepto', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('soporte', models.FileField(blank=True, null=True, upload_to='cuentas_cobro/')),
                ('estado', models.CharField(choices=[('RADICADA', 'Radicada'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada')], default='RADICADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cobro', to='tenancy.empresa')),
                ('proveedor', models.ForeignKey(help_text='Debe ser un tercero tipo Proveedor/Contratista aprobado.', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='terceros.tercero')),
            ],
            options={
                'unique_together': {('empresa', 'proveedor', 'numero')},
            },
        ),
    ]
