# Generated by Django 6.0 on 2025-12-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('terceros', '0003_invitacionvinculacion_tipo_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobro',
            name='proveedor',
            field=models.ForeignKey(limit_choices_to={'estado': 'APROBADO', 'tipos__code__in': ['PROVEEDOR', 'CONTRATISTA']}, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='terceros.tercero'),
        ),
        migrations.CreateModel(
            name='InvitacionRadicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('USADA', 'Usada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.empresa')),
                ('proveedor', models.ForeignKey(limit_choices_to={'estado': 'APROBADO', 'tipos__code__in': ['PROVEEDOR', 'CONTRATISTA']}, on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero')),
            ],
        ),
    ]
