# Generated by Django 6.0 on 2026-01-23 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('proveedores', '0002_alter_cuentacobro_proveedor_invitacionradicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('obligatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='soporte',
        ),
        migrations.RemoveField(
            model_name='cuentacobro',
            name='valor',
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='admon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='imprevistos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='iva_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('RADICADA', 'Radicada'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='periodo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CuentaCobroAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='cuentas_cobro/anexos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='proveedores.cuentacobro')),
                ('tipo_anexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.tipoanexo')),
            ],
        ),
    ]
