# Generated by Django 6.0 on 2026-01-30 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('proveedores', '0003_tipoanexo_remove_cuentacobro_soporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionradicacion',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_radicacion', to='contratos.contrato'),
        ),
    ]
