# Generated by Django 6.0 on 2026-01-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_invitacionradicacion_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionradicacion',
            name='cuenta_cobro',
            field=models.OneToOneField(blank=True, help_text='Borrador de cuenta de cobro asociado a esta invitación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_origen', to='proveedores.cuentacobro'),
        ),
    ]
