# Generated by Django 6.0 on 2026-03-06 21:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_add_cuenta_cobro_to_invitacion'),
        ('tenancy', '0002_alter_empresa_options_alter_empresa_nit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacobro',
            name='ibc_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingreso Base de Cotización reportado para seguridad social', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA aplicable. Editable para persona jurídica.', max_digits=5),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='mes_servicio_date',
            field=models.DateField(blank=True, help_text='Primer día del mes del servicio (para cálculo de acumulado)', null=True),
        ),
        migrations.AddField(
            model_name='cuentacobro',
            name='tipo_documento',
            field=models.CharField(choices=[('CUENTA_COBRO', 'Cuenta de Cobro'), ('FACTURA', 'Factura')], default='CUENTA_COBRO', help_text='Persona natural -> Cuenta de Cobro, Persona jurídica -> Factura', max_length=20),
        ),
        migrations.AddField(
            model_name='tipoanexo',
            name='aplica_a_persona',
            field=models.CharField(choices=[('AMBAS', 'Ambas'), ('NATURAL', 'Solo persona natural'), ('JURIDICA', 'Solo persona jurídica')], default='AMBAS', help_text='Tipo de persona al que aplica este anexo', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionRadicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_minimo_vigente', models.DecimalField(decimal_places=2, default=Decimal('1423500.00'), help_text='Salario mínimo legal mensual vigente (SMLMV)', max_digits=14)),
                ('porcentaje_umbral', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Porcentaje del SMLMV que define el umbral para exigir seguridad social', max_digits=5)),
                ('porcentaje_minimo_ibc', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Porcentaje mínimo del ingreso que debe ser el IBC', max_digits=5)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_radicacion', to='tenancy.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Radicación',
                'verbose_name_plural': 'Configuraciones de Radicación',
            },
        ),
    ]
