# Generated by Django 6.0 on 2026-03-08 15:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_cuentacobro_ibc_valor_cuentacobro_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionradicacion',
            name='porcentaje_umbral',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Porcentaje del SMLMV que define el umbral para exigir seguridad social', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracionradicacion',
            name='salario_minimo_vigente',
            field=models.DecimalField(decimal_places=2, default=Decimal('1750905.00'), help_text='Salario mínimo legal mensual vigente (SMLMV)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='cuentacobro',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
