# Generated by Django 6.0 on 2026-03-09 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_numero_cuenta_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cuentas_cobro/comprobantes/')),
                ('fecha_pago', models.DateField()),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia o transacción', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_cobro', models.ForeignKey(help_text='Cuenta de cobro asociada a este comprobante', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='proveedores.cuentacobro')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
            },
        ),
    ]
