# Generated by Django 6.0 on 2026-01-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('terceros', '0004_tag_alter_tercerotipo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('objeto', models.TextField(help_text='Objeto/descripción del contrato')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='BORRADOR', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contratista', models.ForeignKey(limit_choices_to={'estado': 'APROBADO', 'tipos__code__in': ['PROVEEDOR', 'CONTRATISTA']}, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='terceros.tercero')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='tenancy.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
