# Generated by Django 6.0 on 2026-03-21 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_tipoanexocontrato_tipocontrato'),
        ('terceros', '0008_tercero_info_tributaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dependencia_solicitante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_rl',
            field=models.ForeignKey(blank=True, help_text='Representante legal de la empresa (usuario interno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_como_rl_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_contrato',
            field=models.DateField(blank=True, help_text='Fecha de firma/formalización', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_fin_otrosi',
            field=models.DateField(blank=True, help_text='Nueva fecha fin por otrosí', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tercero_rl',
            field=models.ForeignKey(blank=True, help_text='Representante legal del contratista', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_como_rl', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_otrosi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_polizas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.tipocontrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_sin_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('VIGENTE', 'Vigente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('LIQUIDADO', 'Liquidado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total legado (compatibilidad)', max_digits=18),
        ),
    ]
