# Generated by Django 6.0 on 2026-03-21 12:20

import contratos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_options_contrato_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionContractual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Condición contractual',
                'verbose_name_plural': 'Condiciones contractuales',
                'ordering': ['contrato', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PolizaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.CharField(max_length=200)),
                ('numero_poliza', models.CharField(blank=True, max_length=100)),
                ('amparo', models.CharField(help_text='Nombre del amparo cubierto', max_length=200)),
                ('valor_asegurado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='VIGENTE', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=contratos.models._poliza_upload)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Póliza de contrato',
                'verbose_name_plural': 'Pólizas de contrato',
                'ordering': ['contrato', 'fecha_fin'],
            },
        ),
    ]
