# Generated by Django 6.0 on 2026-03-21 12:22

import contratos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_condicioncontractual_polizacontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text="Hito o cuota (ej. 'Anticipo 30%')", max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha real de pago', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
                'ordering': ['contrato', 'orden', 'fecha_estimada'],
            },
        ),
        migrations.CreateModel(
            name='OtrosiContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número secuencial del otrosí (1, 2, 3…)')),
                ('fecha', models.DateField()),
                ('objeto', models.TextField(help_text='Descripción del otrosí / modificación pactada')),
                ('nuevo_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Nuevo valor total del contrato (si aplica)', max_digits=18, null=True)),
                ('nueva_fecha_fin', models.DateField(blank=True, help_text='Nueva fecha de terminación (si aplica)', null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=contratos.models._otrosi_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrosis', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Otrosí de contrato',
                'verbose_name_plural': 'Otrosíes de contrato',
                'ordering': ['contrato', 'numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
    ]
