# Generated by Django 6.0 on 2026-03-21 12:23

import contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_formapagocontrato_otrosicontrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('archivo', models.FileField(upload_to=contratos.models._anexo_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contratos.contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_anexos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='contratos.tipoanexocontrato')),
            ],
            options={
                'verbose_name': 'Anexo de contrato',
                'verbose_name_plural': 'Anexos de contrato',
                'ordering': ['contrato', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('VIGENTE', 'Vigente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('LIQUIDADO', 'Liquidado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('VIGENTE', 'Vigente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('LIQUIDADO', 'Liquidado'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujo', to='contratos.contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_flujos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flujo de contrato',
                'verbose_name_plural': 'Flujos de contrato',
                'ordering': ['contrato', 'fecha'],
            },
        ),
    ]
